### ISSUE TITLE
请问kitti_00文件夹内数据的路径应该是什么样的？

### ISSUE THREAD

**Issue by hzxbzp** [lturing/vins_fusion_pangolin#1]
作者您好，首先您的工作真的非常出色。我现在尝试运行您的代码，但是出现了如下问题，请问是不是我输入数据的问题？请问kitti_00文件夹内数据的路径应该是什么样的？

运行时出现的问题：
config_file: config/kitti_odom/kitti_config00-02.yaml
vocabulary path: support_files/brief_k10L6.bin
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1014 00:27:49.548521  1131 estimator.cpp:15] init begins
create loop graph
start loading dict
loop start load vocabulary
terminate called after throwing an instance of 'std::length_error'
  what():  vector::reserve
Aborted

**Comment by lturing** [comment]
为kitti_00的根目录
更新了readme
